#            _  _  _                _   
#  ___ __ _ (_)| || |__  ___  __ _ | |_ 
# (_-</ _` || || || '_ \/ _ \/ _` ||  _|
# /__/\__,_||_||_||_.__/\___/\__,_| \__|
                                      
# Basic Setup:
name = "Equation_Painter"
short_name = "equationpainter"
email = "cole@colewilson.xyz"
author = "Cole Wilson"
short_description = "A way for teachers to make equation painter worksheets for their students."
description = "A way for teachers to make equation painter worksheets for their students."
url = "https://github.com/cole-wilson/wsm"
keywords = ""
license = "MIT"
latest_build = "3.1.0+c1545fb.3"
release-notes = "a"
latest_release = "2.0.5"


# Resource Setup:
[resources]
icns = "i.icns"
data_files = [ "web",]
modules = [ "requests", "pillow", "xlsxwriter", "Image", "eel", "gevent",]
file = "main.py"
no_import = [ "random", "os", "mainfile",]


# Plugin Commands:
[command.tasks]


# Build Routines:
[build.pyinstaller]
_run = false
type = 1
mac = true
windows = true
unix = false
options = [ "--hidden-import", "bottle_websocket",]
bundle_id = "xyz.colewilson.equationpainter"

[build.homebrew]

[build.pypi.commands]
eqpaint = "__main__.main"

[build.pypi.entry_points]


# Release Routines:
[release.github_release]


# Other:
[git]
brew = "cole-wilson/homebrew-taps"
github = "cole-wilson/equationpainter"


# Thank you for using Sailboat!